AWSTemplateFormatVersion: '2010-09-09'
Description: Create an Amazon EKS Cluster and Managed Node Group

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster

  KubernetesVersion:
    Type: String
    Default: '1.32'
    AllowedValues: ['1.27', '1.28', '1.29']
    Description: Kubernetes version for the control plane

  ClusterAdminRoleArn:
    Type: String
    Default: '
    Description: IAM Role ARN for EKS control plane

  NodeInstanceRoleArn:
    Type: String
    Description: IAM Role ARN for worker nodes

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where EKS resources will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnets across multiple AZs for EKS

  NodeGroupName:
    Type: String
    Default: acit-nodegroup
    Description: Name of the managed node group

  InstanceTypes:
    Type: List<String>
    Default: ["t3.medium"]
    Description: EC2 instance types for worker nodes

  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired number of worker nodes

  MinSize:
    Type: Number
    Default: 1

  MaxSize:
    Type: Number
    Default: 4

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !Ref ClusterAdminRoleArn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPrivateAccess: false
        EndpointPublicAccess: true

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      NodegroupName: !Ref NodeGroupName
      ClusterName: !Ref EKSCluster
      NodeRole: !Ref NodeInstanceRoleArn
      Subnets: !Ref SubnetIds
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
      AmiType: AL2_x86_64
      InstanceTypes: !Ref InstanceTypes
      DiskSize: 20
      Tags:
        Name: !Ref NodeGroupName
      Labels:
        lifecycle: ec2

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
  ClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
  ClusterArn:
    Value: !Ref EKSCluster
  NodeGroupName:
    Value: !Ref EKSNodeGroup
